### ISSUE TITLE
Πρόβλημα με τιμολόγιο πώλησης.

### ISSUE THREAD

**Issue by sonikf** [evansgl/dolibarr-mydata#1]
Καλημέρα και ευχαριστώ για την σπουδαία δουλειά που κάνεις!
module_mydata-1.4 και module_mydata-1.5
custom/mydata/mydatalist/Iindex.php
Γραμμές 236 και 237 αντίστοιχα πρέπει να αλλάξουν σε  
			$classificationCategory = "category1_1";
			$classificationType = CLASSIFICATION_TYPE_GR;
διαφορετικά δεν εμφανίζει τίποτα στην λίστα όταν κόβω τιμολόγιο πώλησης.

**Comment by evansgl** [comment]
Ευχαριστώ,
Eχει διορθωθεί ήδη στην  1.4
