### ISSUE TITLE
Δεν συμπληρώνει το MARK σε odt template

### ISSUE THREAD

**Issue by VaderD** [evansgl/dolibarr-mydata#11]
Στην έκδοση 16.0.1 η μεταβλητή σε odt template ή {object_options_mydata_reply} είναι κενή (δεν συμπληρώνεται) με αποτέλεσμα να μην μπαίνει σε odt template

**Comment by sonikf** [comment]
Δεν έχει να κάνει με το mydata ειναι bug σε 16.0.0 και 16.0.1
Δες εδώ για προσωρινή λύση.
https://github.com/Dolibarr/dolibarr/issues/22312

**Comment by sonikf** [comment]
@evansgl 
Μπορείς να το κλείσεις έχει φτιαχτεί από την 16.0.2
