### ISSUE TITLE
Αναβάιμιση σε Dolibarr 17.0.0

### ISSUE THREAD

**Issue by VaderD** [evansgl/dolibarr-mydata#17]
Σε τεστ περιβάλλον που έκανα με dolibarr 17 βγάζει το παρακάτω λάθος

[10-Mar-2023 16:31:42 Europe/Athens] PHP Fatal error:  Uncaught Error: Undefined constant "INVOICE_APODIXI_NUM" in /localhost/test/public_html/dolibarr-3.6.0/htdocs/custom/mydata/mydatalist/index.php:350
Stack trace:
#0 /localhost/test/public_html/dolibarr-3.6.0/htdocs/custom/mydata/mydataindex.php(104): include_once()
#1 {main}
  thrown in /localhost/test/public_html/dolibarr-3.6.0/htdocs/custom/mydata/mydatalist/index.php on line 350

Version Dolibarr: 17.0.0
OS: Rocky Linux 9.1 (Blue Onyx)
Web Server: Apache/2.4.53
PHP: 8.1.1.16
MySQL: 10.5.16

Οπότε αν δεν υπάρξει νεώτερη έκδοση μην προβείτε σε αναβάθμιση.....

**Comment by evansgl** [comment]
Δεν έχει κάποιο θέμα ακόμα και με latest dolibarr
