### ISSUE TITLE
αριθμος παραστατικου σε ΑΑΔΕ

### ISSUE THREAD

**Issue by sonikf** [evansgl/dolibarr-mydata#2]
Δεν ξέρω αν είναι bug ή αν έχω κάνει εγώ κάποια λάθος ρύθμιση.

Ένα παραστατικό που έχω ανεβάσει όλο και όλο στην ΑΑΔΕ με την 1.4 εμφανίζεται έτσι όταν κάνω προβολή παραστατικού μέσα απο το myDATA της ΑΑΔΕ

![AADE](https://user-images.githubusercontent.com/93765174/140730344-b6921bf6-dc50-47b1-8cd0-f73c48a5e571.png)
ενώ το παραστατικό είναι της μορφής ΤΙΜ-{yyyy}-{0000) και έχω ενεργοποιήσει το Όνομα Παραστατικού στα settings.

**Comment by evansgl** [comment]
Είναι bug. Η έκδοση 1.5 το διορθώνει.
