### ISSUE TITLE
Πρόβλημα με ευρωπαϊκά ΑΦΜ που συμπεριέχουν γράμματα εκτός από ψηφία

### ISSUE THREAD

**Issue by diplaros** [evansgl/dolibarr-mydata#34]
Σε κάποιες ευρωπαϊκές χώρες το ΑΦΜ μπορεί να περιέχει χαρακτήρες εκτός ψηφίων (έχω συγκεκριμένα παραδείγματα από Κύπρο και Ολλανδία όπου υπάρχει γράμμα στη μέση ή στο τέλος του ΑΦΜ). Όπως είναι τώρα ο κώδικας (δηλαδή $vat = preg_replace('/\D/', '', $row["tva_intra"])) αφαιρεί όλους τους χαρακτήρες  και το ΑΦΜ που ανεβαίνει στην ΑΑΔΕ είναι λάθος. 

Απαιτείται αλλαγή στο mydata/mydatalist/index.php στην γραμμή 181. Δηλαδή από 

while ($row = $result->fetch_assoc()) 
{

.....
	**_$vat = preg_replace('/\D/', '', $row["tva_intra"]);_**

θα πρέπει να αλλαχθεί σε 

	**$vat = preg_replace('/\^\w/', '', $row["tva_intra"]);
	$vat = str_replace(array(' ', '.'), '', $vat);
	$countryCode = substr($vat, 0, 2);
	if (strlen(preg_replace('/\D/', '', $countryCode))==0) // if contryCode is only letters then do remove them
	{	
		$vat = substr($vat, 2);
	}**

ώστε να διατηρεί χαρακτήρες που βρίσκονται στο "εσωτερικό" ενός ΑΦΜ ενώ, εάν αρχίζει με κωδικό χώρας, να τον αφαιρεί από το ΑΦΜ που θα πάει στην ΑΑΔΕ.

**Comment by evansgl** [comment]
Ok, thanks, Θα το φτιάξω
