### ISSUE TITLE
Error when Pushing invoices to MyData

### ISSUE THREAD

**Issue by giannhsa** [evansgl/dolibarr-mydata#35]
I got the following error when trying to send data to aade test environment

PHP Fatal error:  Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'http://www.aade.gr/myDATA/invoice/v1.0:type' element is invalid - The value '...' at line 1 in /var/www/html/custom/mydata/mydatalist/mydata.php:237\nStack trace:\n#0 /var/www/html/custom/mydata/mydatalist/mydata.php(237): mysqli_query()\n#1 /var/www/html/custom/mydata/mydatalist/index.php(428): include('...')\n#2 /var/www/html/custom/mydata/mydataindex.php(104): include_once('...')\n#3 {main}\n  thrown in /var/www/html/custom/mydata/mydatalist/mydata.php on line 237, referer: http://<MyIP>:<MyPort>/custom/mydata/mydataindex.php

Also from the logs i see a 403 response code on the Post Request.

"POST /custom/mydata/mydataindex.php?idmenu=18337&mainmenu=mydata&leftmenu= HTTP/1.0" 403 831 "http://<MyIp>:<MyPort>/custom/mydata/mydataindex.php?idmenu=18337&mainmenu=mydata&leftmenu=" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"

Im using plugin version 1.8.1 with Dolibarr v19.0.0

Also these the data tables below:
![Screenshot 2024-02-15 171710](https://github.com/evansgl/dolibarr-mydata/assets/44959808/23553fb8-4309-4056-9a44-66b0e9439ca7)

Any ideas whats the issues here? The goal is to push the invoices to mydata and get back the QR code

**Comment by sonikf** [comment]
Ηι @giannhsa 
Some remarks and questions
test clients info should be valid/real
what is your php version? try first with php 7.4
v. 19.0.0 is just released and some changes need to be done to the module, better try with v 18.0.5 for now
403 usually indicates problem with insufficient rights

**Comment by giannhsa** [comment]
Hello, thanks for your response.
I changed my versions to 18.0.5 and 7.4
I send the the invoices to myData I get the green check and also the reply date and code but when I refresh the list it is shown again as not sent.
When I checked the logs I still have the 403 request.
Any suggestions?

**Comment by giannhsa** [comment]
Thanks a lot. This solved my issue.
Finally I tried to add the Url from AADE reply into a document.
I use the {object_options_mydata_reply_QR} in the odt template but instead of getting the Url I get the text Επιβεβαίωση Παραστατικού

**Comment by sonikf** [comment]
This method doesn't work for the QR and odt, check the Greek community [forum](https://www.dolibarr.gr/foroum/topics.html) for possible solutions
My suggestion is to try the mydata pdf solution with sponge template(see mydata settings) or use [Mask4Greece](https://github.com/TechnickSysAid/mask4greece)
