### ISSUE TITLE
Λάθος ανεβασμα παραστατικού

### ISSUE THREAD

**Issue by VaderD** [evansgl/dolibarr-mydata#8]
Σε ένα τιμολόγιο το όποιο από λάθος δεν είχε χαρακτηρισμό ως πιστωτικό τιμολόγιο αλλά είχε αρνητικές αξίες αυτός το ανέβασε ως κανονικό βάσει του χαρακτηρισμού. Το πιστωτικό αυτό είχε δημιουργηθεί με το κουμπί "Δημιουργία Πιστωτικού Σημειώματος" 

Κανονικά εφόσον είδε αρνητικές αξίες δεν έπρεπε να το ανεβάσει και να βγάλει λάθος ώστε να το δει ο χρήστης.
Άλλα αν πει κάποιος ότι θα το ανεβάζει θα έπρεπε να σταλεί ως πιστωτικό γιατί παραστατικό εκτός πιστωτικού δεν υπάρχει με αρνητικές αξίες...

**Comment by evansgl** [comment]
H ααδε δεν δέχεται αρνητικές αξίες. Πρέπει αναγκαστικά να το περάσεις σαν πιστωτικό με θετικά ποσά
