### ISSUE TITLE
Fatal error σε Dolibarr 16.0.0 PHP 8.0 και PHP 8.1

### ISSUE THREAD

**Issue by sonikf** [evansgl/dolibarr-mydata#9]
`Fatal error: Uncaught Error: Undefined constant "INVOICE_APODIXI_NUM" in /custom/mydata/mydatalist/index.php:350 Stack trace: #0 /custom/mydata/mydataindex.php(104): include_once() #1 {main} thrown in /custom/mydata/mydatalist/index.php on line 350`

Αφαιρώντας τον σχετικό κώδικα το module παίζει κανονικά για τα τιμολόγια(δεν χρησιμοποιώ αποδείξεις!).
Σε PHP 7.4 όλα ok
Επίσης εμφανίζονται και τα παρακάτω.

```
Warning: Undefined property: stdClass::$MYDATA_INV_TYPE_GR in /custom/mydata/mydatalist/config.php on line 21

Warning: Undefined property: stdClass::$MYDATA_INV_TYPE_EU in /custom/mydata/mydatalist/config.php on line 22

Warning: Undefined property: stdClass::$MYDATA_INV_TYPE_3RD in /custom/mydata/mydatalist/config.php on line 23

Warning: Undefined property: mysqli_result::$connect_errno in /custom/mydata/mydatalist/index.php on line 77
```

**Comment by evansgl** [comment]
Thanks. θα το διορθώσω
